pdsweb/mysite/dama/urls.py
from . import views
from django.urls import path

app_name = 'dama'


urlpatterns = [
    path('', views.IndexView.as_view(), name='index'), #ok

    path('cadastro/', views.CadastroView.as_view(), name='cadastro'), #ok

    path('denuncia/', views.DenunciaView.as_view(), name='denuncia'), #ok

    path('mural/', views.MuralView.as_view(), name='mural'), #ok

    path('relato/', views.RelatoView.as_view(), name='relato'), #ok

    path('login/', views.LogarView.as_view(), name='login'), #ok

    path('logout/', views.LogoutView.as_view(), name='logout'), #ok

    path('perfil/', views.PerfilView.as_view(), name='perfil'), #ok

    path('material/', views.CadastroMaterialView.as_view(), name='material'), #ok

    path('material/<int:id>', views.MaterialDetailView, name='material-detail'), #ok

    path('materiais', views.MateriaisView.as_view(), name="materiais"), #ok
    
    path('editar/', views.EditarPerfilView.as_view(), name='editar'),

    path('delete/', views.DeletePerfilView.as_view(), name='delete'), #ok
]

pdsweb/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dama/', include('dama.urls'))
]

pdsweb/mysite/dama/forms.py
import re
from django import forms
from .models import Usuario, UsuarioOng, UsuarioProfissional
from .models import Relato
from django.core.validators import RegexValidator


class UsuarioAnonimoForm(forms.Form):
    senha = forms.CharField(min_length=8, widget=forms.PasswordInput)
    class Meta:
        model = Usuario
        fields = ['nome_login', 'senha']


class UsuarioOngForm(forms.Form):
    nome_login = forms.CharField(label='Nome de Usuario')
    
    senha = forms.CharField(min_length=8, widget=forms.PasswordInput, label='Senha')
    
    razao_social = forms.CharField(min_length=1, label='Razão Social')
    
    cnpj = forms.CharField(min_length=14, max_length=14, label='CNPJ')
    
    email = forms.EmailField(label='Email')

    validador_telefone = RegexValidator(
        regex=r'^\d{2}\s*\d{5}-\d{4}$',
        message='Número de telefone inválido. Formato esperado: 84 91234-5678'
    )

    telefone = forms.CharField(
        label='Contato',
        validators=[validador_telefone],
        max_length=14
    )
    
    class Meta:
        model = UsuarioOng
        fields = ['nome_login', 'senha', 'razao_social', 'cnpj', 'email', 'telefone']


class UsuarioProfissionalForm(forms.Form):
    nome_login = forms.CharField(label='Nome de Usuario')
    
    senha = forms.CharField(min_length=8, widget=forms.PasswordInput, label='Senha')
    
    nome_completo = forms.CharField(max_length=100, label='Nome Completo')

    validador_crp = RegexValidator(
        regex=r'^\d{2}\s*\d{5}$',
        message='CRP inserido é inválido'
        )

    cadastro_crp = forms.CharField(
        min_length=9,
        validators=[validador_crp], 
        label='CRP'
        )
    
    email = forms.EmailField(label='Email')

    validador_telefone = RegexValidator(
        regex=r'^\d{2}\s*\d{5}-\d{4}$',
        message='Número de telefone inválido. Formato esperado: 84 91234-5678'
    )

    telefone = forms.CharField(
        label='Contato',
        validators=[validador_telefone],
        max_length=14
    )
    
    class Meta:
        model = UsuarioOng
        fields = ['nome_login', 'senha', 'nome_completo', 'cadastro_crp', 'email', 'telefone']


# class DenunciaForm(forms.Form):
#     descricao_denuncia = forms.CharField(label='Descrição')
    
#     idade_vitima = forms.IntegerField(label='Idade da Vitima')

#     tipo_local = forms.CharField(label='Local da Violência')

#     relacao_autor = forms.CharField(label='Relação com Agressor')

#     zona_cidade = forms.CharField(label='Zona da Cidade Onde Ocorreu a Violência')

#     vitima_tipo = forms.CharField(label='Vitima da Agressão')

#     class Meta:
#         model = Denuncia
#         fields = ['idade_vitima', 'vitima_tipo', 'relacao_autor', 'tipo_local', 'zona_cidade', 'descricao_denuncia']

class RelatoForm(forms.ModelForm):
    texto_relato = forms.CharField(widget=forms.Textarea, label='texto_relato')

    class Meta:
        model = Relato
        fields = ['texto_relato']





# class Teste(forms.ModelForm):
#     senha = forms.CharField(min_length=1, widget=forms.PasswordInput)

#     confirmar_senha = forms.CharField(
#         min_length=1,
#         widget=forms.PasswordInput,
#         label='Confirmar Senha'
#     )

#     class Meta:
#         model = Usuario
#         fields = ['nome_login', 'senha']

#     def clean(self):
#         cleaned_data = super().clean()

#         senha = cleaned_data.get("senha")

#         confirmar_senha = cleaned_data.get("confirmar_senha")

#         if senha is not None and confirmar_senha is not None and senha != confirmar_senha:
#             self.add_error('confirmar_senha', 'As senhas não coincidem.')

#         return cleaned_data

pdsweb/mysite/dama/views.py
import re
from .models import *
from django.views import View
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, HttpResponseRedirect, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash


class IndexView(View):
    def get(self, request, *args, **kwargs):
        return render(request, "index.html")


class CadastroView(View):
    def get(self, request,*args, **kwargs):
        return render(request, "cadastro.html")
    
    def post(self, request, *args, **kwargs):
        dados_requisicao = request.POST

        if 'nome_login' in dados_requisicao and 'senha' in dados_requisicao:
            nome_login = dados_requisicao.get('nome_login')

            senha = dados_requisicao.get('senha')

            # se for profissional
            if 'crp' in dados_requisicao and 'nome_completo' in dados_requisicao:
                nome_completo = dados_requisicao.get('nome_completo')

                crp = dados_requisicao.get('crp')

                email = dados_requisicao.get('email')


                contato = dados_requisicao.get('contato')

                validacao_contato = re.search(r'^\d{2}\s*\d{9}$', contato)

                # se o contato não foi validado
                if validacao_contato is None:
                    return render(request, "cadastro.html", context={'erro': 'contato invalido'})

                else:

                    usuario = User.objects.create_user(
                        username=nome_login,
                        password=senha,
                        email=email
                    )

                    novo_usuario = UsuarioProfissional.objects.create(
                        nome_login=nome_login,
                        senha=senha,
                        nome_completo=nome_completo,
                        cadastro_crp=crp,
                        email=email,
                        telefone=contato,
                        usuario = usuario,
                    )

                    novo_usuario.save()
                
            # se for ong
            if 'cnpj' in dados_requisicao and 'razao_social' in dados_requisicao:
                razao_social = dados_requisicao.get('razao_social')

                cnpj = dados_requisicao.get('cnpj')

                email = dados_requisicao.get('email')

                contato = dados_requisicao.get('contato')

                validacao_contato = re.search(r'^\d{2}\s*\d{9}$', contato)

                # se o contato não foi validado
                if validacao_contato is None:
                    return render(request, "cadastro.html", context={'erro': 'contato invalido'})

                else:
                    usuario = User.objects.create_user(
                        username=nome_login,
                        password=senha,
                        email=email
                    )

                    novo_usuario = UsuarioOng.objects.create(
                        nome_login=nome_login,
                        senha=senha,
                        razao_social=razao_social,
                        cnpj=cnpj,
                        email=email,
                        telefone=contato,
                        usuario = usuario,
                    )

                    novo_usuario.save()
                

            # se for anonimo
            else:        
                usuario = User.objects.create_user(
                        username=nome_login,
                        password=senha,
                )     

                novo_usuario = UsuarioAnonimo.objects.create(
                        nome_login=nome_login,
                        senha=senha,
                        usuario = usuario,
                    )

                novo_usuario.save()
                
            return redirect(reverse('dama:index'))

        else:
            return render(request, 'cadastro.html', context={'erro': 'preencha o login e senha'})


class LogarView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'login.html')

    def post(self, request, *args, **kwargs):
        dados_requisicao = request.POST

        if 'nome_login' in dados_requisicao and 'senha_usuario' in dados_requisicao:
            nome_login = dados_requisicao.get('nome_login')
            senha = dados_requisicao.get('senha_usuario')

            usuario = authenticate(username=nome_login, password=senha)

            if usuario is not None:
                login(request, usuario)
                next_url = request.POST.get('next')
                if next_url:
                    return redirect(next_url)
                else:
                    return redirect(reverse('dama:index'))
            else:
                return render(request, 'login.html', {'erro': 'Nome de usuário ou senha incorretos.'})
        else:
            return render(request, 'login.html', {'erro': 'Por favor, preencha todos os campos.'})


class LogoutView(View):
        def post(self, request, *args, **kwargs):
            logout(request)
            return HttpResponseRedirect(reverse('dama:index'))
        

class EditarPerfilView(View):
    def get(self, request, *args, **kwargs):
        
        if request.user.is_authenticated:
            usuario = request.user 

            contexto = {}

            if hasattr(usuario, 'usuarioanonimo'):

                contexto['tipo_usuario'] = 'anonimo'

            elif hasattr(usuario, 'usuarioprofissional'):

                contexto['tipo_usuario'] = 'profissional'
            
            elif hasattr(usuario, 'usuarioong'):

                contexto['tipo_usuario'] = 'ong'
            
            else:

                contexto['tipo_usuario'] = 'problema_usuario'

            return render(request, "editar.html", context=contexto)
        

        return render(request, "crud.html")

    def post(self, request, *args, **kwargs):

        if request.user.is_authenticated:

            contexto = {}

            usuario_logado = request.user 

            dados_requisicao = request.POST

            if 'nome_login' in dados_requisicao and 'senhaa' in dados_requisicao:

                nome_login = dados_requisicao.get('nome_login')

                senha = dados_requisicao.get('senhaa')

                if hasattr(usuario_logado, 'usuarioanonimo'):

                    usuario = UsuarioAnonimo.objects.get(usuario=usuario_logado)

                    if usuario is not None:
                        
                        usuario.nome_login = nome_login

                        usuario.senha = senha
                        
                        usuario.save()

                        usuario.usuario.username = nome_login

                        usuario.usuario.email = email

                        usuario.usuario.set_password(senha) 

                        usuario.usuario.save()

                        update_session_auth_hash(request, usuario.usuario)

                        return HttpResponseRedirect(reverse('dama:perfil'))

                    else:
                        contexto = {
                            'mensagem': 'usuario não foi encontrado no banco'
                        }
                    

                elif hasattr(usuario_logado, 'usuarioprofissional'):

                    usuario = UsuarioProfissional.objects.get(usuario=usuario_logado)

                    if usuario is not None:

                        if 'crp' in dados_requisicao and 'nome_completo' in dados_requisicao:

                            nome_completo = dados_requisicao.get('nome_completo')

                            crp = dados_requisicao.get('crp')

                            email = dados_requisicao.get('email')

                            contato = dados_requisicao.get('contato')

                            validacao_contato = re.search(r'^\d{2}\s*\d{9}$', contato)

                            usuario.nome_login = nome_login

                            usuario.senha = senha

                            usuario.nome_completo = nome_completo

                            usuario.cadastro_crp = crp

                            usuario.email = email

                            usuario.telefone = contato

                            usuario.save()

                            usuario.usuario.username = nome_login

                            usuario.usuario.email = email

                            usuario.usuario.set_password(senha) 

                            usuario.usuario.save()

                            update_session_auth_hash(request, usuario.usuario)

                            return HttpResponseRedirect(reverse('dama:perfil'))
                        
                    else:
                        contexto = {
                            'mensagem_erro': 'usuario não foi encontrado no banco'
                        }

                
                elif hasattr(usuario_logado, 'usuarioong'):

                    usuario = UsuarioOng.objects.get(usuario=usuario_logado)

                    if usuario is not None:

                        if 'cnpj' in dados_requisicao and 'razao_social' in dados_requisicao:

                            razao_social = dados_requisicao.get('razao_social')

                            cnpj = dados_requisicao.get('cnpj')

                            email = dados_requisicao.get('email')

                            contato = dados_requisicao.get('contato')

                            validacao_contato = re.search(r'^\d{2}\s*\d{9}$', contato)

                            usuario.nome_login = nome_login

                            usuario.senha = senha
                            
                            usuario.razao_social = razao_social

pdsweb/mysite/dama/templates/Relato.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet" href="{% static 'css/header.css' %}" />
    <link rel="stylesheet" href="{% static 'css/relato.css' %}" />
    <link rel="stylesheet" href="{% static 'css/footer.css' %}" />


    <title>Mural de Força</title>
  </head>

  <body>
    <header id="cabecalho" class="borda0">
      <div class="borda0 header-div header-div-left">
        <a href="{% url 'dama:index' %}">
          <img id="logo-img" src="{% static 'img/logo-dama.png' %}" alt="logomarca do Dama" />
        </a>
      </div>
      <nav class="borda0 header-nav">
        <ul>
          <li><a href="{% url 'dama:index' %}">Home</a></li>
          <li><a href="#">Quem Somos</a></li>
          <li><a href="{% url 'dama:materiais' %}">Conheça seus direitos</a></li>
          <li><a href="#">Rede de apoio</a></li>
          <li><a href="{% url 'dama:mural' %}">Mural de Força</a></li>
        </ul>
      </nav>
      <div class="borda0 header-div-right">

        {% if request.user.is_authenticated %}

        <div id="usuario-logado" class="borda2">
                <a href="{% url 'dama:perfil' %}">{{ request.user.username }}!</a>
            </div>
        
        <div id="logout" class="borda2">
          <form method="post" action="{% url 'dama:logout' %}" style="display: inline;">
            {% csrf_token %}
            <button class="button-header" type="submit">Sair</button>
          </form>
        </div>

        {% else %}

        <button id="header-login" class="button-header">
          <a href="{% url 'dama:login' %}">Login</a>
        </button>
        <button id="header-conta" class="button-header">
          <a href="{% url 'dama:cadastro' %}">Criar Conta</a>
        </button>

        {% endif %}
      </div>
    </header>

    <main id="main">

      <div id="main-div" class="borda0">
        <table class="borda0">
            <thead id="thead">
                <tr id="thead" class="borda0">
                    <th id="mural" class="borda0" colspan="5">Envie seu relato</th>
                </tr>
                
            </thead>
            <tbody class="borda0">
              <tr>
                <td colspan="5" class="borda0">
                  <form method="post">
                    {% csrf_token %}
                    <textarea type="text" id="relato" name="text" placeholder="Escreva seu relato" style="vertical-align: top;" ></textarea>
                    <button type="submit" id="filtroButton">Publicar</button>
                  </form>
                </td>
              </tr>
            </tbody>
        </table>
      </div>
    </main>
    <footer class="footer">
        <div class="footer-div footer-div-left borda0">
            <p>emergencia?</p>
            <h1><span>ligue 180</span></h1>
        </div>
        <div class="footer-div footer-div-center borda0">
          <div class="footer-div-center-top borda0" >
              <h1>Ajuda</h1>
          </div>
          <div class="footer-div-center-bottom borda0">
            <p><a href="#">Sobre nós</a></p>
            <p><a href="#">Seja apoiador</a></p>
            <p><a href="#">Seja voluntário</a></p>
            <p><a href="{% url 'dama:materiais' %}">Conheça seus direitos</a></p>
          </div>
        </div>
        <div class="footer-div footer-div-right borda0">
          <img src="{% static 'img/logo_rn.png' %}" alt="">
        </div>
    </footer>

  </body>
</html>

pdsweb/mysite/dama/templates/cadastro.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet" href="{% static 'css/header.css' %}" />
    <link rel="stylesheet" href="{% static 'css/cadastro-main.css' %}" />
    <link rel="stylesheet" href="{% static 'css/footer.css' %}" />

    <title>Cadastro</title>

    <style>
      main {
    min-height: 520px;
    padding: 5px;

    background-color: rgba(240, 229, 223, 0.8);
    background-image: url("{% static 'img/bg-cadastro.png' %}");
    background-size: auto;
    background-repeat: no-repeat;
    background-blend-mode: hard-light;
    background-position: bottom left;
    
    justify-content: center;
    align-items: center;
    display: flex;
    font-size: 18px;
     
}
    </style>

  </head>

  <body>
    <header class="borda0 header">
      <div class="borda0 header-div header-div-left">
                <a href="{% url 'dama:index' %}">
          <img id="logo-img" src="{% static 'img/logo-dama.png' %}" alt="logomarca do Dama" />
        </a>
      </div>
      <nav class="borda0 header-nav">
        <ul>
          <li><a href="{% url 'dama:index' %}">Home</a></li>
          <li><a href="#">Quem Somos</a></li>
          <li><a href="{% url 'dama:materiais' %}">Conheça seus direitos</a></li>
          <li><a href="#">Rede de apoio</a></li>
          <li><a href="{% url 'dama:mural' %}">Mural de Força</a></li>
        </ul>
      </nav>
      <button id="bttdenuncia" class="button-header">
        <a href="{% url 'dama:denuncia' %}">Denunciar</a>
      </button>
      <div class="borda0 header-div-right">
        <button id="header-login" class="button-header">
          <a href="{% url 'dama:login' %}">Entrar</a>
        </button>

        
      </div>
    </header>

    <main id="main" class="borda0">
      <div class="div-form">
        <form class="borda0 form" action="{% url 'dama:cadastro' %}" method="post" name="cadastro">
          {% csrf_token %}

          <h1>Cadastro</h1>
          <label for="nome_login" >Nome de Login</label>
          <input type="text" id="nome" name="nome_login" placeholder="Login de acesso ao DAMA" onfocus="removePlaceholder(this.id)" onblur="addPlaceholder(this.id)">
          
          <label for="senha">Senha</label>
          <div>
            <input type="password" id="senha" name="senha" placeholder="Digite sua senha"  onfocus="removePlaceholder(this.id)" onblur="addPlaceholder(this.id)">
            <span class="visibilidade-senha" onclick="visibilidadeSenha('senha')">👁️</span>
          </div>
        

          <label for="usuario">Tipo de Usuário</label>
          <select id="usuario" name="usuario" form="cadastro" onchange="mostrarCampos(this.value)">
            <option value="anom">Anonimo</option>
            <option value="ong">Organização Não-Governamental</option>
            <option value="pro">Profissional de Apoio</option>
          </select>

          <label id="nome-usuario-label" class="hidden" for="nome-usuario-input"></label>
          <input id="nome-usuario-input" class="hidden" type="text"  name=""  maxlength="100" onfocus="removePlaceholder(this.id)" onblur="addPlaceholder(this.id)" pattern="[0-9]"/>
          

          <label id="numero-cadastro-label" class="hidden" for="numero-cadastro-input"></label>
          <input id="numero-cadastro-input" class="hidden" type="text"  name=""  maxlength="14" onfocus="removePlaceholder(this.id)" onblur="addPlaceholder(this.id)" pattern="[0-9]"/>
           
          <fieldset class="borda0">
            <div id="fieldset-left">
              <label for="email" class="hidden">Email</label>
              <input id="email" class="hidden" type="email"  name="email" placeholder="exemplo@email.com" maxlength="30" onfocus="removePlaceholder(this.id)" onblur="addPlaceholder(this.id)" pattern="[a-zA-Z0-9._@-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"/> 
            </div>
            <div id="fieldset-right">
              <label for="contato" class="hidden">Contato</label>
              <input id="contato" class="hidden" type="tel"  name="contato" placeholder="84 9XXXX-XXXX" maxlength="14" onfocus="removePlaceholder(this.id)" onblur="addPlaceholder(this.id)" pattern="[a-zA-Z0-9._@-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"/>  
            </div>
          </fieldset>

          <div id="submeter" class="borda0">
            <div id="cancelar" class="borda0">
              <button class="button-form">Cancelar</button>
            </div>
            <div id="criar" class="borda0">
              <button id="confirmar-button" class="button-form" type="submit" >Cadastrar</button>
            </div>
          </div>
          <input type="hidden" name="next" value="{{ request.GET.next }}">
        </form>
      </div>
    </main>

    <div id="cadastrado" class="oculto borda0">
      <div class="cadastrado-janela borda0">
          <h1>
            Usuaria(o) cadastrada(o) com sucesso!<br>
          </h1>
      </div>
      <div class="cadastrado-janela borda0">
          <h1>
            <span onclick="Login()">Acesse o DAMA com a sua nova conta aqui</span>            
          </h1>
      </div>
    </div>

    <footer class="borda0">
      <div class="footer-div footer-div-left borda0">
          <p>emergencia?</p>
          <h1><span>ligue 180</span></h1>
      </div>
      <div class="footer-div footer-div-center borda0">
        <div class="footer-div-center-top borda0" >
            <h1>Ajuda</h1>
        </div>

        <div class="footer-div-center-bottom borda0">
          <p><a href="#">Sobre nós</a></p>
          <p><a href="#">Seja apoiador</a></p>
          <p><a href="#">Seja voluntário</a></p>
          <p><a href="{% url 'dama:materiais' %}">Conheça seus direitos</a></p>
        </div>

      </div>

      <div class="footer-div footer-div-right borda0">
        <img src="{% static 'img/logo_rn.png' %}" alt="">
      </div>
  </footer>

    <script src="{% static 'js/muda_janela.js' %}"></script>
    <script src="{% static 'js/cadastro.js' %}"></script>
  </body>
</html>

pdsweb/mysite/dama/templates/confirmacao.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>confirmacao</title>
</head>
<body>
    <p>
        {{ dados_requisicao }}
    </p>
    
</body>
</html>

pdsweb/mysite/dama/templates/materiais.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet" href="{% static 'css/header.css' %}" />
    <link rel="stylesheet" href="{% static 'css/materiais.css' %}" />
    <link rel="stylesheet" href="{% static 'css/footer.css' %}" />

    <title>Materiais Publicados</title>
  </head>

  <body>
    <header>
        <div class="borda0 header-div header-div-left">
            <a href="{% url 'dama:index' %}">
                <img id="logo-img" src="{% static 'img/logo-dama.png' %}" alt="logomarca do Dama" />
            </a>
            </div>
            <nav class="borda0 header-nav">
            <ul>
                <li><a href="{% url 'dama:index' %}">Home</a></li>
                <li><a href="#main-div2">Quem Somos</a></li>
                <li><a href="#redes">Rede de apoio</a></li>
                <li><a href="{% url 'dama:mural' %}">Mural de Força</a></li>
            </ul>
            </nav>
        
            {% if request.user.is_authenticated %}
        
            <div id="usuario-logado" class="borda2">
                <a href="{% url 'dama:perfil' %}">{{ request.user.username }}!</a>
            </div>
            
            <div id="logout" class="borda2">
                <form method="post" action="{% url 'dama:logout' %}" style="display: inline;">
                <button class="button-header" type="submit">Sair</button>
                </form>
            </div>
        
            {% else %}
        
            <button id="header-login" class="button-header">
                <a href="{% url 'dama:login' %}">Login</a>
            </button>
            <button id="header-conta" class="button-header">
                <a href="{% url 'dama:cadastro' %}">Criar Conta</a>
            </button>
        
            {% endif %}
            </div>
        </header>



    <main id="main" class="borda0">
        {% block content %}
        <div class="materiais-container">
            <h1>Materiais Publicados</h1>

            {% if materiais %}
                <div class="materiais-grid">
                    {% for material in materiais %}
                        <div class="material-card">
                            <a href="{% url 'dama:material-detail' material.id %}" class="material-link">
                                <h3>{{ material.usuario.username }}</h3>
                                <p class="data-publicacao">Data: {{ material.data_publicacao|date:"d/m/Y H:i" }}</p>
                                <p class="material-conteudo">{{ material.conteudo|truncatechars:150 }}</p> <!-- Limita a 150 caracteres -->
                            </a>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <p>Nenhum material publicado até o momento.</p>
            {% endif %}
        </div>
        {% endblock %}
        </main>


        <footer class="borda0">
            <div class="footer-div footer-div-left borda0">
                <p>emergencia?</p>
                <h1><span>ligue 180</span></h1>
            </div>
            <div class="footer-div footer-div-center borda0">
              <div class="footer-div-center-top borda0" >
                  <h1>Ajuda</h1>
              </div>
      
              <div class="footer-div-center-bottom borda0">
                <p><a href="#">Sobre nós</a></p>
                <p><a href="#">Seja apoiador</a></p>
                <p><a href="#">Seja voluntário</a></p>
                <p><a href="{% url 'dama:materiais' %}">Conheça seus direitos</a></p>
              </div>
      
            </div>
      
            <div class="footer-div footer-div-right borda0">
              <img src="{% static 'img/logo_rn.png' %}" alt="">
            </div>
          </footer>
      
        </body>
      </html>
      

pdsweb/mysite/dama/templates/perfil.html
{% load static %}


<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet" href="{% static 'css/header.css' %}" />
    <link rel="stylesheet" href="{% static 'css/index-main.css' %}" />
    <link rel="stylesheet" href="{% static 'css/footer.css' %}" />

    <title>Perfil</title>
</head>

<body>

    {% if not mensagem_erro %}
        <h1>Manter perfil do usario - {{ nome_login }} </h1>
        <h2>Tipo do Usuario: {{ tipo_usuario }}</h2>

        {% if tipo_usuario == 'profissional' %}
            <p>Nome Completo: {{ nome_completo }}</p>
            <p>Cadastro CRP: {{ cadastro_crp }}</p>
            <p>Telefone: {{ telefone }}</p>
            <p>Email: {{ email }}</p>


        {% elif tipo_usuario == 'ong' %}
            <p>Razão Social: {{ razao_social }}</p>
            <p>CNPJ: {{ cnpj }}</p>
            <p>Telefone: {{ telefone }}</p>
            <p>Email: {{ email }}</p>

        {% else %}
            <p style="color: red;">{{ mensagem_erro }}</p>
        {% endif %}    

    {% endif %}

    <button id="atualizar-conta" class="button-header">
        <a href="{% url 'dama:index' %}">Atualizar Perfil</a>
    </button>
    
    <button id="deletar-conta" class="button-header">
        <a href="{% url 'dama:index' %}">Excluir Perfil</a>
    </button>



    <button id="voltar" class="button-header">
        <a href="{% url 'dama:index' %}">Voltar</a>
    </button>

    <div id="excluir">
        
    </div>
</body>

</html>